// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa96RyU3dZThJAVp2uvG46PqjNPdnE_RA',
    appId: '1:293537462263:web:2ce11c5bcbac6e8a3560f2',
    messagingSenderId: '293537462263',
    projectId: 'admobtest-b5032',
    authDomain: 'admobtest-b5032.firebaseapp.com',
    storageBucket: 'admobtest-b5032.firebasestorage.app',
    measurementId: 'G-NERVYKDCCW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkTZQGER5wTCym-9CCFsn11ZYMVJe5i50',
    appId: '1:293537462263:android:e506174e739d2fc63560f2',
    messagingSenderId: '293537462263',
    projectId: 'admobtest-b5032',
    storageBucket: 'admobtest-b5032.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjrZs05DHWLgMB1dLaA8m7kcUPUv7jxFw',
    appId: '1:293537462263:ios:c6e6a9486a9b13d53560f2',
    messagingSenderId: '293537462263',
    projectId: 'admobtest-b5032',
    storageBucket: 'admobtest-b5032.firebasestorage.app',
    iosBundleId: 'com.example.admobtest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjrZs05DHWLgMB1dLaA8m7kcUPUv7jxFw',
    appId: '1:293537462263:ios:c6e6a9486a9b13d53560f2',
    messagingSenderId: '293537462263',
    projectId: 'admobtest-b5032',
    storageBucket: 'admobtest-b5032.firebasestorage.app',
    iosBundleId: 'com.example.admobtest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCa96RyU3dZThJAVp2uvG46PqjNPdnE_RA',
    appId: '1:293537462263:web:cedaee491a2265353560f2',
    messagingSenderId: '293537462263',
    projectId: 'admobtest-b5032',
    authDomain: 'admobtest-b5032.firebaseapp.com',
    storageBucket: 'admobtest-b5032.firebasestorage.app',
    measurementId: 'G-0MWFKK511K',
  );
}
